dist: focal
language: minimal

branches:
  only:
  - main

services:
- docker

install:
# login to dockerhub
- echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
# install kubectl
- curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
# get kubeconfig from travis secret
- mkdir .kube
- echo ${KUBECONFIG} | base64 -d > .kube/config

script:
# building & pushing image to dockerhub
- docker build -t mirdhyn/litecoin:${TRAVIS_COMMIT} .
- docker push mirdhyn/litecoin:${TRAVIS_COMMIT}
# get latest commit sha & use it in kustomize instead of latest
# note: yes, I know... there's much simplier/better way to do that, but I needed to use some text manipulation here
- git log| grep commit| head -1| awk '{print $2}'| xargs -I{} sed -i 's/latest/{}/' deploy/kustomization.yaml
# deploy to cluster
- ./kubectl apply -k deploy
# check that app is running 
- ./kubectl get po -lapp=litecoin
- sleep 15
- ./kubectl logs -lapp=litecoin

