apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  selector:
    matchLabels:
      app: litecoin
  serviceName: litecoin
  replicas: 1
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      containers:
      - name: litecoin
        image: mirdhyn/litecoin:0.18.1
        volumeMounts:
        - name: data
          mountPath: /.litecoin
        resources:
          limits:
            cpu: 1
            memory: 100Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi # for testing only
